version: '3.1'

services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"  # Ánh xạ cổng 80 của container vào cổng 8080 trên máy host
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_NAME: exampledb
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: rootpassword
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  wordpress_data:
  mysql_data:
