version: '3'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_USER: sa
      MYSQL_PASSWORD: sapassword
      MYSQL_DATABASE: mydb
    ports:
      - "3307:3306"  # Chỉnh cổng host từ 3306 thành 3307
  
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - mysql
